-- 코드를 입력하세요
SELECT c.AUTHOR_ID, c.AUTHOR_NAME, a.CATEGORY, SUM(a.PRICE * b.SALES) AS TOTAL_SALES
FROM AUTHOR c
JOIN BOOK a ON c.AUTHOR_ID = a.AUTHOR_ID
JOIN BOOK_SALES b ON a.BOOK_ID = b.BOOK_ID
WHERE YEAR(SALES_DATE) = '2022' AND MONTH(SALES_DATE) = '01'
GROUP BY c.AUTHOR_ID, a.CATEGORY
ORDER BY c.AUTHOR_ID, a.CATEGORY DESC;
