(SELECT DATE_FORMAT(SALES_DATE, "%Y-%m-%d") AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE
WHERE SALES_DATE >= STR_TO_DATE('2022-03-01', '%Y-%m-%d')
AND SALES_DATE <= STR_TO_DATE('2022-03-31', '%Y-%m-%d') 

UNION

SELECT DATE_FORMAT(SALES_DATE, "%Y-%m-%d") AS SALES_DATE, PRODUCT_ID, NULL AS USER_ID , SALES_AMOUNT
FROM OFFLINE_SALE
WHERE SALES_DATE >= STR_TO_DATE('2022-03-01', '%Y-%m-%d')
AND SALES_DATE <= STR_TO_DATE('2022-03-31', '%Y-%m-%d') )
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID